In [2]:
import numpy as np
import pandas as pd

In [3]:
data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': [
        'East', 'West', 'North', 'South',
        'East', 'West', 'North', 'South',
        'East', 'West', 'North', 'South',
        'East', 'West', 'North', 'South',
        'East', 'West', 'North', 'South'
    ],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': [
        'John', 'Mary', 'Bob', 'Alice',
        'John', 'Mary', 'Bob', 'Alice',
        'John', 'Mary', 'Bob', 'Alice',
        'John', 'Mary', 'Bob', 'Alice',
        'John', 'Mary', 'Bob', 'Alice'
    ]
}

df = pd.DataFrame(data)

df['Month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)

In [4]:
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    276     65   John  January      Q1
1  2023-01-02       B   West    510     24   Mary  January      Q1
2  2023-01-03       C  North    302     87    Bob  January      Q1
3  2023-01-04       D  South    602     66  Alice  January      Q1
4  2023-01-05       A   East    994     32   John  January      Q1
5  2023-01-06       B   West    989     30   Mary  January      Q1
6  2023-01-07       C  North    676     15    Bob  January      Q1
7  2023-01-08       D  South    242     57  Alice  January      Q1
8  2023-01-09       A   East    845     20   John  January      Q1
9  2023-01-10       B   West    914     26   Mary  January      Q1
10 2023-01-11       C  North    540     78    Bob  January      Q1
11 2023-01-12       D  South    926     93  Alice  January      Q1
12 2023-01-13       A   East    162     67   John  January      Q1
13 2023-01-14       B   West    709     63   Mary  January      Q1
14 2023-01-15       C  North    872     37    Bob  January      Q1
15 2023-01-16       D  South    177     24  Alice  January      Q1
16 2023-01-17       A   East    146     12   John  January      Q1
17 2023-01-18       B   West    217     74   Mary  January      Q1
18 2023-01-19       C  North    284     74    Bob  January      Q1
19 2023-01-20       D  South    170     39  Alice  January      Q1

# Pivot Tables

In [8]:
pivot1 = pd.pivot_table(df, values='Sales', index = 'Region', columns='Product', aggfunc='sum')
pivot1

Product       A       B       C       D
Region
East     2423.0     NaN     NaN     NaN
North       NaN     NaN  2674.0     NaN
South       NaN     NaN     NaN  2117.0
West        NaN  3339.0     NaN     NaN

In [9]:
pd.pivot_table(df, values=['Sales', 'Units'], index = 'Region', columns='Product', aggfunc='sum')

          Sales                          Units
Product       A       B       C       D      A      B      C      D
Region
East     2423.0     NaN     NaN     NaN  196.0    NaN    NaN    NaN
North       NaN     NaN  2674.0     NaN    NaN    NaN  291.0    NaN
South       NaN     NaN     NaN  2117.0    NaN    NaN    NaN  279.0
West        NaN  3339.0     NaN     NaN    NaN  217.0    NaN    NaN

# Cross Tabs

In [10]:
pd.crosstab(df['Region'], df['Product'])

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0